### ISSUE TITLE
Use "deprecated" meta instead of traces

### ISSUE THREAD

**Issue by boozook** [peteshand/haxe-starling#11]
Please use `@:deprecated` or `@:deprecated("you message")` instead of traces like [this](https://github.com/peteshand/haxe-starling/blob/master/src/starling/core/RenderSupport.hx#L197).

(See ref. in [manual](http://haxe.org/manual/cr-metadata.html))

**Comment by boozook** [comment]
:+1:

**Comment by peteshand** [comment]
yep, good call
