### ISSUE TITLE
Work with Shared Context

### ISSUE THREAD

**Issue by boozook** [peteshand/haxe-starling#12]
This issue more look like a question, sorry about this.
I get a troubles when I trying to run your Starling impl. with shared context3D. My workflow:
- init [Zame particles](https://github.com/restorer/zame-haxe-particles/)
- init Starling;
- listening ENTER_FRAME and doing

``` haxe
sharedStage3D.context3D.clear();
mStarling.nextFrame();
sharedStage3D.context3D.present();
```

But Starling are not drawing anything. Pete, what I doing wrong?

**Comment by peteshand** [comment]
have you tried mStarling.render(); instead of mStarling.nextFrame();

**Comment by boozook** [comment]
Yes. Anyway black viewport instead needed.

**Comment by boozook** [comment]
Oh. Not Starling's viewport is black, but all stage3D's viewport black.

**Comment by peteshand** [comment]
if you share your source code I can take a look

**Comment by boozook** [comment]
Sorry, we are under NDA and we refused to use your Starling impl.
