### ISSUE TITLE
Render texture example doesn't work 

### ISSUE THREAD

**Issue by Seb-AS** [peteshand/haxe-starling#17]
Hi, I was testing your code, after updated to latest openfl the starling example render texture doesn't draw(html5), thanks for the great work

**Comment by peteshand** [comment]
Hi Sab, Yes I'm aware of this issue and am working on resolving it, there are actually a lot of breaking changes with the latest OpenFL and Lime update, particularly with the use of emuns and the flash target. I'll keep you posted.

**Comment by Seb-AS** [comment]
Thanks for your quick reply

**Comment by peteshand** [comment]
Quick update. This issue has been resolved in a local branch, however I need to get some OpenFL pull requests approved before I can push.

**Comment by peteshand** [comment]
Hi Seb-AS
If you pull starling from Haxelib this issue is resolved.

**Comment by Seb-AS** [comment]
Thanks Peter!!
