### ISSUE TITLE
Can't compile original-demo for mac target

### ISSUE THREAD

**Issue by lzaiats** [peteshand/haxe-starling#19]
I get those errors:

Luizs-MacBook-Pro:original-demo luiz.zaiats$ openfl test mac
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/net/URLLoader.hx:274: characters 16-34 : openfl.utils.ByteArray has no field readFile
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/net/URLLoader.hx:353: characters 34-48 : openfl.utils.ByteArray has no field asString
bin/mac64/cpp/haxe/DefaultAssetLibrary.hx:542: characters 7-27 : Type not found : lime.utils.ByteArray
/private/var/haxelib/lime/2,8,1/lime/Assets.hx:37: lines 37-883 : Defined in this class
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/display/BitmapData.hx:556: characters 2-18 : openfl.utils.ByteArray has no field checkData
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/display/BitmapData.hx:595: characters 3-19 : openfl.utils.ByteArray has no field setLength (Suggestions: set_length, get_length)
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/display/BitmapData.hx:672: characters 3-19 : openfl.utils.ByteArray has no field setLength (Suggestions: set_length, get_length)
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/utils/ArrayBufferView.hx:68: characters 2-18 : openfl.utils.ByteArray has no field bigEndian
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/utils/ArrayBufferView.hx:71: characters 10-24 : openfl.utils.ByteArray has no field getData
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/utils/Float32Array.hx:119: characters 2-18 : openfl.utils.ByteArray has no field setLength (Suggestions: set_length, get_length)
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/gl/GL.hx:918: characters 81-101 : openfl.utils.ByteArray has no field getByteBuffer
/private/var/haxelib/openfl/3,5,3/openfl/_legacy/gl/GL.hx:918: characters 129-144 : openfl.utils.ByteArray has no field getStart
/private/var/haxelib/openfl/3,5,3/openfl/utils/ByteArray.hx:228: lines 228-776 : Field endian has different type than in openfl._legacy.utils.IDataOutput
/private/var/haxelib/openfl/3,5,3/openfl/utils/ByteArray.hx:228: lines 228-776 : openfl.utils.Endian should be String
/private/var/haxelib/openfl/3,5,3/openfl/utils/ByteArray.hx:604: lines 604-614 : Field writeBytes has different type than in openfl._legacy.utils.IDataOutput
/private/var/haxelib/openfl/3,5,3/openfl/utils/ByteArray.hx:604: lines 604-614 : bytes : openfl.utils.ByteArray -> ?offset : UInt -> ?length : UInt -> Void should be bytes : haxe.io.Bytes -> ?offset : Int -> ?length : Int -> Void
/private/var/haxelib/openfl/3,5,3/openfl/utils/ByteArray.hx:604: lines 604-614 : openfl.utils.ByteArray should be haxe.io.Bytes
/private/var/haxelib/openfl/3,5,3/openfl/utils/ByteArray.hx:228: lines 228-776 : Field endian has different type than in openfl._legacy.utils.IDataInput
/private/var/haxelib/openfl/3,5,3/openfl/utils/ByteArray.hx:228: lines 228-776 : openfl.utils.Endian should be String

**Comment by peteshand** [comment]
What version of lime are you on?

**Comment by lzaiats** [comment]
Luizs-MacBook-Pro:export luiz.zaiats$ haxelib list
actuate: [1.8.6]
debugger: git [dev:/private/var/haxelib/debugger/git]
format: [3.2.1]
hxcpp: [3.2.193]
lime: [2.8.1]
openfl: 3.5.2 [3.5.3]
starling: [0.4.0]

**Comment by peteshand** [comment]
does the following help.
In project.xml change
`<set name="lime-hybrid" />`
to
`<set name="next" />`

**Comment by lzaiats** [comment]
It worked! Thank you!

**Comment by peteshand** [comment]
Good to hear!
Another option would be to package an Desktop AIR version.
